import { logger } from "./logger";
import crypto from "crypto";

/**
 * QueryHandler — answers community questions about a launch.
 * 
 * AI Authority:
 * - MAY answer factual questions about launch status, charter, metrics
 * - MAY explain policy mechanics
 * - MAY NOT provide financial advice or price predictions
 * - All responses include advisory disclaimer
 */
export class QueryHandler {
  private modelId = "bondit-advisory-v1";

  async handleQuery(launchId: string, question: string): Promise<QueryResponse> {
    const queryType = this.classifyQuery(question);
    logger.info({ launchId, queryType, questionLength: question.length }, "QueryHandler: processing");

    const promptHash = crypto.createHash("sha256")
      .update(`query_${launchId}_${question}_${Date.now()}`)
      .digest("hex")
      .slice(0, 16);

    let answer: string;

    switch (queryType) {
      case "status":
        answer = await this.answerStatusQuery(launchId);
        break;
      case "charter":
        answer = await this.answerCharterQuery(launchId);
        break;
      case "treasury":
        answer = await this.answerTreasuryQuery(launchId);
        break;
      case "flight_mode":
        answer = await this.answerFlightModeQuery(launchId);
        break;
      case "fees":
        answer = await this.answerFeesQuery(launchId);
        break;
      case "mechanics":
        answer = this.answerMechanicsQuery(question);
        break;
      default:
        answer = "I can help with questions about this launch's status, charter parameters, treasury, flight mode progress, fees, and how the Agency system works. What would you like to know?";
    }

    return {
      launchId,
      question,
      answer,
      queryType,
      modelId: this.modelId,
      promptHash,
      timestamp: Date.now(),
      disclaimer: "ADVISORY ONLY — This response is generated by AI for informational purposes. It does not constitute financial advice. The AI cannot execute trades or modify protocol parameters.",
    };
  }

  private classifyQuery(question: string): string {
    const q = question.toLowerCase();
    if (q.includes("status") || q.includes("phase") || q.includes("graduated")) return "status";
    if (q.includes("charter") || q.includes("rules") || q.includes("parameters")) return "charter";
    if (q.includes("treasury") || q.includes("release") || q.includes("supply")) return "treasury";
    if (q.includes("flight") || q.includes("sunset") || q.includes("holders")) return "flight_mode";
    if (q.includes("fee") || q.includes("revenue") || q.includes("house")) return "fees";
    if (q.includes("how") || q.includes("what") || q.includes("explain")) return "mechanics";
    return "general";
  }

  private async answerStatusQuery(_launchId: string): Promise<string> {
    // TODO: Fetch from indexer
    return "This launch is currently in the Stewardship phase. The bonding curve has graduated and the Agency is actively managing liquidity and treasury releases according to the charter.";
  }

  private async answerCharterQuery(_launchId: string): Promise<string> {
    return "The charter defines: daily release rate of 0.20% of remaining treasury, max daily release of 1M tokens, max weekly release of 5M tokens, 99/1 fee split (LP/House), and flight mode triggers at 15K holders + ≤18% top-10 concentration + ≤5% treasury remaining.";
  }

  private async answerTreasuryQuery(_launchId: string): Promise<string> {
    return "The Agency Treasury started with 150M tokens (15% of total supply). Releases follow exponential decay (0.20% of remaining per day), capped at 1M tokens/day and 5M tokens/week. Released tokens primarily flow into LP depth.";
  }

  private async answerFlightModeQuery(_launchId: string): Promise<string> {
    return "Flight Mode triggers when ALL conditions are met: 15,000+ holders, top-10 concentration ≤18%, and treasury remaining ≤5%. There's also a 180-day forced sunset. Once triggered, Agency stewardship stops permanently.";
  }

  private async answerFeesQuery(_launchId: string): Promise<string> {
    return "Protocol fees are 1% on each curve trade. Post-graduation, LP fees are harvested daily and split 99% back to LP (compounding) and 1% to the house. House fees stop at Flight Mode.";
  }

  private answerMechanicsQuery(_question: string): string {
    return "The BondIt.lol Agency system provides transparent, deterministic stewardship during a token's early life. A bonding curve handles the initial trading phase (targeting 85 SOL graduation). After graduation, the Agency manages liquidity on Meteora DLMM, releases treasury tokens gradually, and compounds LP fees — all governed by immutable charter rules. The AI is advisory only and cannot trade or change parameters.";
  }
}

export interface QueryResponse {
  launchId: string;
  question: string;
  answer: string;
  queryType: string;
  modelId: string;
  promptHash: string;
  timestamp: number;
  disclaimer: string;
}
