import { logger } from "./logger";
import crypto from "crypto";
import type {
  LaunchDashboardResponse,
  LaunchFeeBreakdownResponse,
  LaunchFlightStatusResponse,
  LaunchLiquidityStatsResponse,
  LaunchListItem,
  LaunchTreasuryResponse,
  PolicyActionLog,
} from "@bondit/sdk/api";

const INDEXER_API_BASE = process.env.INDEXER_API_URL ?? process.env.NEXT_PUBLIC_INDEXER_API_URL ?? "http://localhost:3001/api";

type ReportData = {
  status: string;
  dayNumber: number;
  holdersCount: number;
  priceChange24h: string;
  volume24h: string;
  treasuryRemaining: string;
  treasuryRemainingPct: number;
  releasedToday: string;
  nextReleaseEstimate: string;
  lpDepthUsd: string;
  feesHarvested: string;
  compounded: string;
  houseShare: string;
  top10Concentration: string;
  holdersGrowth: string;
  newHolders24h: number;
  flightEligible: boolean;
  holdersProgress: number;
  concentrationProgress: number;
  treasuryProgress: number;
  daysRemaining: number;
  recentActions: PolicyActionLog[];
  anomalies: Array<Record<string, unknown>>;
};

async function fetchJson<T>(url: string): Promise<T> {
  const response = await fetch(url, {
    headers: { "Content-Type": "application/json" },
  });

  if (!response.ok) {
    let details = `Request failed with status ${response.status}`;
    try {
      const payload = (await response.json()) as { error?: string; details?: string };
      details = payload.details ? `${payload.error ?? details}: ${payload.details}` : payload.error ?? details;
    } catch {}
    throw new Error(details);
  }

  return (await response.json()) as T;
}

function formatSignedPercent(value?: number | null): string {
  if (typeof value !== "number" || !Number.isFinite(value)) return "unavailable";
  return `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;
}

function formatBpsPercent(value?: number | null): string {
  if (typeof value !== "number" || !Number.isFinite(value)) return "unavailable";
  return `${(value / 100).toFixed(2)}%`;
}

function computeForwardProgress(current: number, target: number): number {
  if (!Number.isFinite(target) || target <= 0) return 0;
  return Math.max(0, Math.min(100, Number(((current / target) * 100).toFixed(2))));
}

function computeInverseProgress(current: number, target: number): number {
  if (!Number.isFinite(current) || current <= 0) return 100;
  if (!Number.isFinite(target) || target <= 0) return 0;
  if (current <= target) return 100;
  return Math.max(0, Math.min(100, Number(((target / current) * 100).toFixed(2))));
}

/**
 * ReportGenerator — generates daily/weekly transparency reports.
 * 
 * AI Authority Boundaries:
 * - MAY generate reports
 * - MAY NOT execute trades or modify parameters
 * - All outputs logged with prompt hash, model id, timestamp, disclaimer
 */
export class ReportGenerator {
  private modelId = "bondit-advisory-v1";

  async generateDailyReport(launchId: string): Promise<TransparencyReport> {
    logger.info({ launchId }, "Generating daily transparency report");

    // TODO: Fetch data from indexer API
    const data = await this.fetchLaunchData(launchId);

    const report: TransparencyReport = {
      launchId,
      reportType: "daily",
      generatedAt: Date.now(),
      modelId: this.modelId,
      promptHash: this.hashPrompt(`daily_report_${launchId}_${Date.now()}`),
      disclaimer: "ADVISORY ONLY — This report is generated by AI and does not constitute financial advice. AI cannot execute trades or modify protocol parameters.",

      summary: {
        status: data.status,
        dayNumber: data.dayNumber,
        holdersCount: data.holdersCount,
        priceChange24h: data.priceChange24h,
        volume24h: data.volume24h,
      },

      treasury: {
        remaining: data.treasuryRemaining,
        remainingPct: data.treasuryRemainingPct,
        releasedToday: data.releasedToday,
        releaseSchedule: data.nextReleaseEstimate,
      },

      liquidity: {
        lpDepthUsd: data.lpDepthUsd,
        feesHarvested: data.feesHarvested,
        compounded: data.compounded,
        houseShare: data.houseShare,
      },

      distribution: {
        top10Concentration: data.top10Concentration,
        holdersGrowth: data.holdersGrowth,
        newHolders24h: data.newHolders24h,
      },

      flightMode: {
        eligible: data.flightEligible,
        holdersProgress: data.holdersProgress,
        concentrationProgress: data.concentrationProgress,
        treasuryProgress: data.treasuryProgress,
        daysRemaining: data.daysRemaining,
      },

      policyActions: data.recentActions,

      anomalies: data.anomalies,
    };

    logger.info({
      launchId,
      reportType: "daily",
      promptHash: report.promptHash,
    }, "Daily report generated");

    return report;
  }

  async generateWeeklyReport(launchId: string): Promise<TransparencyReport> {
    logger.info({ launchId }, "Generating weekly transparency report");

    // Similar to daily but with weekly aggregates
    const dailyReport = await this.generateDailyReport(launchId);
    dailyReport.reportType = "weekly";
    dailyReport.promptHash = this.hashPrompt(`weekly_report_${launchId}_${Date.now()}`);

    return dailyReport;
  }

  private hashPrompt(input: string): string {
    return crypto.createHash("sha256").update(input).digest("hex").slice(0, 16);
  }

  private async fetchLaunchData(launchId: string): Promise<ReportData> {
    const dashboard = await fetchJson<LaunchDashboardResponse>(`${INDEXER_API_BASE}/launches/${encodeURIComponent(launchId)}/dashboard`);

    const [launchResult, treasuryResult, liquidityResult, flightResult, feesResult] = await Promise.allSettled([
      fetchJson<LaunchListItem>(`${INDEXER_API_BASE}/launches/${encodeURIComponent(launchId)}`),
      fetchJson<LaunchTreasuryResponse>(`${INDEXER_API_BASE}/launches/${encodeURIComponent(launchId)}/treasury`),
      fetchJson<LaunchLiquidityStatsResponse>(`${INDEXER_API_BASE}/launches/${encodeURIComponent(launchId)}/liquidity`),
      fetchJson<LaunchFlightStatusResponse>(`${INDEXER_API_BASE}/launches/${encodeURIComponent(launchId)}/flight-status`),
      fetchJson<LaunchFeeBreakdownResponse>(`${INDEXER_API_BASE}/launches/${encodeURIComponent(launchId)}/fees`),
    ]);

    const launch = launchResult.status === "fulfilled" ? launchResult.value : null;
    const treasury = treasuryResult.status === "fulfilled" ? treasuryResult.value : null;
    const liquidity = liquidityResult.status === "fulfilled" ? liquidityResult.value : null;
    const flight = flightResult.status === "fulfilled" ? flightResult.value : null;
    const fees = feesResult.status === "fulfilled" ? feesResult.value : null;

    const anomalies: Array<Record<string, unknown>> = [];

    if (!launch) anomalies.push({ type: "missing_metric", metric: "launch_overview" });
    if (!treasury) anomalies.push({ type: "missing_metric", metric: "treasury" });
    if (!liquidity) anomalies.push({ type: "missing_metric", metric: "liquidity" });
    if (!flight) anomalies.push({ type: "missing_metric", metric: "flight_status" });
    if (!fees) anomalies.push({ type: "missing_metric", metric: "fees" });

    const nextReleaseEstimate = treasury?.releaseSchedule[0]
      ? `${treasury.releaseSchedule[0].amount} to ${treasury.releaseSchedule[0].destination}`
      : "No indexed release schedule";

    const holdersProgress = flight
      ? computeForwardProgress(flight.conditions.holdersCount, flight.conditions.holdersTarget)
      : 0;
    const concentrationProgress = flight
      ? computeInverseProgress(flight.conditions.top10ConcentrationBps, flight.conditions.top10Target)
      : 0;
    const treasuryProgress = flight
      ? computeInverseProgress(flight.conditions.treasuryRemainingBps, flight.conditions.treasuryTarget)
      : 0;
    const daysRemaining = flight
      ? Math.max(0, flight.conditions.maxDays - flight.conditions.daysSinceGraduation)
      : 0;

    if (!launch) {
      anomalies.push({ type: "missing_metric", metric: "new_holders_24h" });
    } else {
      anomalies.push({ type: "missing_metric", metric: "holders_growth_24h", message: "Historical holder delta is not yet indexed." });
    }

    return {
      status: dashboard.status,
      dayNumber: dashboard.stewardship.dayNumber,
      holdersCount: dashboard.stewardship.holdersCount,
      priceChange24h: formatSignedPercent(launch?.priceChange24hPct ?? null),
      volume24h: launch?.volume24hUsd ?? "unavailable",
      treasuryRemaining: treasury?.remaining ?? dashboard.stewardship.treasuryRemaining,
      treasuryRemainingPct: treasury?.remainingPct ?? dashboard.stewardship.treasuryRemainingPct,
      releasedToday: treasury?.releasedToday ?? "unavailable",
      nextReleaseEstimate,
      lpDepthUsd: liquidity?.lpDepthUsd ?? dashboard.stewardship.lpDepthUsd,
      feesHarvested: liquidity?.totalFeesHarvested ?? fees?.totalFeesCollected ?? "unavailable",
      compounded: liquidity?.totalCompounded ?? fees?.lpFeesCompounded ?? "unavailable",
      houseShare: fees?.houseFeesCollected ?? "unavailable",
      top10Concentration: formatBpsPercent(dashboard.stewardship.top10ConcentrationBps),
      holdersGrowth: "unavailable",
      newHolders24h: 0,
      flightEligible: flight?.eligible ?? false,
      holdersProgress,
      concentrationProgress,
      treasuryProgress,
      daysRemaining,
      recentActions: dashboard.recentActions,
      anomalies,
    };
  }
}

export interface TransparencyReport {
  launchId: string;
  reportType: "daily" | "weekly";
  generatedAt: number;
  modelId: string;
  promptHash: string;
  disclaimer: string;
  summary: {
    status: string;
    dayNumber: number;
    holdersCount: number;
    priceChange24h: string;
    volume24h: string;
  };
  treasury: {
    remaining: string;
    remainingPct: number;
    releasedToday: string;
    releaseSchedule: string;
  };
  liquidity: {
    lpDepthUsd: string;
    feesHarvested: string;
    compounded: string;
    houseShare: string;
  };
  distribution: {
    top10Concentration: string;
    holdersGrowth: string;
    newHolders24h: number;
  };
  flightMode: {
    eligible: boolean;
    holdersProgress: number;
    concentrationProgress: number;
    treasuryProgress: number;
    daysRemaining: number;
  };
  policyActions: any[];
  anomalies: any[];
}
